### ISSUE TITLE
تصميم واجهة مطابقة لبرنامج المفرغ

### ISSUE THREAD

**Issue by yshalsager** [ieasybooks/almufarrigh#2]
![image](https://user-images.githubusercontent.com/17043808/231499744-b3f95ee9-8c7b-46ef-9711-97684b71f585.png)
![image](https://user-images.githubusercontent.com/17043808/231499360-c5510714-b51d-442d-8ce0-15cb2cf6ff4f.png)
![image](https://user-images.githubusercontent.com/17043808/231499474-dc3b740a-f41b-4f22-98f4-12093e64003d.png)
![image](https://user-images.githubusercontent.com/17043808/231499661-ded102f1-7603-4e9d-ba93-e7e99a0f910f.png)
![image](https://user-images.githubusercontent.com/17043808/231499230-ecd98e54-70d7-485c-9407-be127229c576.png)

**Comment by abdoemr11** [comment]
لا حاجة لهذه التذكرة بعد الآن في وجود التصميم الجديد
