### ISSUE TITLE
دعم العربية والانجليزية 

### ISSUE THREAD

**Issue by abdoemr11** [ieasybooks/almufarrigh#27]
# وصف التذكرة
يوجد خيار في الاعدادات لتغيير لغة العرض بين العربية والانجليزية لكن لا أدري هل هناك ترجمات متفق عليها مسبقا أم لا وأيضا الفيجما لا أري فيها دعما للانجليزية 
# تصنيف التذكرة
تم

# الاختبار:
اكتب كيفية اختبار هذه التذكرة بعد تنفيذها لنتأكد من عملها بهيئة سليمة.

# المتطلبات السابقة:
](https://doc.qt.io/qt-5/qtquick-internationalization.html)

# المهام:
- تحديد الترجمة المناسبة للكلمات العربية في الواجهة
- تنفيذ ذلك في الكود

# أفكار مستقبلية
أضف أفكارًا مستقبلية أو أفكارًا بخصوص هذه الميزة.

# ملاحظات إضافية
أضف أي ملاحظات أو أفكار. 

# branches & pull request:
عند العمل علي هذه التذكرة يجب أن تلتزم بقواعد التسمية كالأتي 
- branch: `feature/<issueNr>/support_arabic_english`
- pull request: `feature-<issueNr>-support_arabic_english`

**Comment by abdoemr11** [comment]
@AliOsm @yshalsager

**Comment by AliOsm** [comment]
لماذا قد نحتاج ترجمة انجليزية للبرنامج؟

**Comment by abdoemr11** [comment]
هذا ما وجدته في تصميم الفيجما

**Comment by AliOsm** [comment]
أظن أنه يمكننا الاستغناء عنه

**Comment by yshalsager** [comment]
> أظن أنه يمكننا الاستغناء عنه

أتفق. على الأقل حاليا.
