### ISSUE TITLE
استخدام GitHub Project 

### ISSUE THREAD

**Issue by abdoemr11** [ieasybooks/almufarrigh#4]
السلام عليكم
حتي لايضيع الوقت والجهد وخاصة لطبيعة البرنامج وكون العمل عليه تطوعيا وعن بعد فأنا اقترح استخدام GitHub Project لادارة ال issues المختلفة ومحاولة تطبيق مفاهيم الأجايل agile بقدر الامكان وسأضرب مثالا حتي تتضح الصورة: 
لنفترض اننا عقدنا اجتماعا واتفقنا علي بعض المميزات الجديده، فسنقوم بانشاء issues لكل ميزة. كل issue ستمر باربع مراحل حتي ننتهي منها وهي backlog - ready - 
sprint- done 
 فسنقوم بانشاء issues لكل ميزة ونضعها في مرحلة backlog مع وضع الوسم المناسب لها مثل gui - refactor - documentation ويفضل أن تكون مجموعة ثابتة من الوسوم، وفي كل issue -سأترجمها تذكرة- توضع تفاصيلها والنقاشات عليها. 
بعد ذلك يحدد الوقت التقريبي اللازم لانهاء التذكرة وتوضع في سلة ready. 
ثم يعقد اجتماع ويحدد كل مشارك ما مقدار الساعات التي يستطيع ان يشارك بها في sprint القادم حيث يحدد sprint بفترة زمنية ولنقل انه اسبوعين. ويحدد أيضا في الاجتماع ما هي التذاكر التي ستوضع في سلة sprint حيث يبدأ المبرمجون في تطويرها. التذكرة التي تنتهي تترك سلة sprint  وتبقي في مثواها الأخير في سلة done 
مارأيكم في هذه الفكرة وما مقترحاتكم؟ انا اقترحت GitHub Project لانه سهل وسلس ويدعم أتمتة العمليات

**Comment by abdoemr11** [comment]
@yshalsager https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects

**Comment by yshalsager** [comment]
@AliOsm 
نحتاج إنشاء [مشروع](https://github.com/orgs/ieasybooks/projects?query=is%3Aopen+sort%3Aupdated-desc) جديد ضمن المنظمة ثم [ربطه](https://github.com/ieasybooks/almufarrigh/projects?query=is%3Aopen) بمستودع المفرغ.

**Comment by AliOsm** [comment]
@yshalsager 
تم إنشاء المشروع ومنحتك صلاحيات الإدارة عليه.

https://github.com/orgs/ieasybooks/projects/1

**Comment by yshalsager** [comment]
@abdoemr11 أضفتك إلى المشروع مع صلاحيات الكتابة

**Comment by abdoemr11** [comment]
تم انشاء المشروع بنجاح
