### ISSUE TITLE
انشاء نموذج أولي 

### ISSUE THREAD

**Issue by abdoemr11** [ieasybooks/almufarrigh#7]
# وصف التذكرة
انشاء نموذج أولي من البرنامج باستخدام التقنيات المتفق عليها مع مراعاة التوثيق التام لبيئة العمل المستخدمة كما هو مذكور هنا #5 

# تصنيف التذكرة
اختر تصنيفا وحيدا مناسبا للتذكرة من التبويب الجانبي.

# الاختبار:
يكفي هنا فقط نافذة بها بعض widget البسيطة 

# المتطلبات السابقة:
اكتب علي ماذا تعتمد هذه التذكرة.

# المهام:
في حالة كبر التذكرة قمسها لعدة مهام أصغر.
يمكنك الإشارة إلى التذاكر بأرقامها أو روابطها، مثل هذا:
- [x] #165

# أفكار مستقبلية
أضف أفكارًا مستقبلية أو أفكارًا بخصوص هذه الميزة.

# ملاحظات إضافية
أضف أي ملاحظات أو أفكار. 

# branches & pull request:
عند العمل علي هذه التذكرة يجب أن تلتزم بقواعد التسمية كالأتي 
- branch: `feat/7/startup_prototype`
- pull request: `feat-7-startup_prototype`

**Comment by abdoemr11** [comment]
@Al-Taie

**Comment by Al-Taie** [comment]
> @Al-Taie 

you did an amazing job 👏
@abdoemr11

**Comment by yshalsager** [comment]
أقترح الاعتماد على هذا القالب
https://github.com/MihailCosmin/cookiecutter-python-gui-application

**Comment by abdoemr11** [comment]
> أقترح الاعتماد على هذا القالب https://github.com/MihailCosmin/cookiecutter-python-gui-application

ما رأيك @Al-Taie ؟

**Comment by Al-Taie** [comment]
> ما رأيك @Al-Taie ؟
لا أراه خياراً جيداً، لا نحتاجه

**Comment by abdoemr11** [comment]
هل تستطيع تولي هذه المهمة حاليا؟ @Al-Taie  أري أنك الأنسب لها
